theme: jekyll-theme-cayman
title: Alexis J. Idlette-Wilson, MLIS
description: Data-Informed Business Analyst Skilled in Statistics and Data Visualization
linkedin: https://www.linkedin.com/in/idlettewilson/
