theme: jekyll-theme-cayman
name: Data Product Manager | Jacksonville FL | Alexis Idlette Wilson
title: Alexis J. Idlette-Wilson, MLIS
description: Data Product Manager in the HCM Technology Space
linkedin: https://www.linkedin.com/in/idlettewilson/
github: alexisidlettewilson
