theme: jekyll-theme-cayman
name: Data Analyst | Jacksonville FL | Alexis Idlette Wilson
title: Alexis J. Idlette-Wilson, MLIS
description: Data-Informed Business Analyst Skilled in Statistics and Data Visualization
linkedin: https://www.linkedin.com/in/idlettewilson/
twitter: alexisidlette
github: alexisidlettewilson
